language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - windows
  - osx
script:
  - cargo test --verbose
  - cargo build --verbose
jobs:
  include:
  - language: nix
    cache:
      directories:
      - $HOME/nix.store
