[package]
name = "onefetch"
description = "Git project summary on your terminal"
version = "1.6.0"
authors = ["o2sh <ossama-hjaji@live.fr>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/onefetch"

[dependencies]
colored= "1.6.1"
git2 = {version = "0.7.5", default-features = false}
tokei = "10.0"
license = "0.7.1"
bytecount = "0.5.1"
clap = "2.33.0"
