[package]
name = "onefetch"
description = "Git repository summary on your terminal"
version = "2.3.0"
authors = ["o2sh <ossama-hjaji@live.fr>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/onefetch"
exclude = ["assets/*.png"]

[package.metadata.deb]
extended-description = """\
Onefetch is a command line tool that displays information about your Git repository directly on your terminal. \
Onefetch supports almost 50 different programming languages. If your language of choice isn't supported: Open up an issue and support will be added. \
"""
depends = "$auto"
section = "utility"
priority = "optional"

[dependencies]
colored= "1.8.0"
git2 = {version = "0.13.6", default-features = false}
tokei = "12.0.0"
askalono = "0.4.0"
bytecount = "0.6.0"
clap = "2.33.0"
strum = "0.18.0"
strum_macros = "0.18.0"
image = "0.22.3"
regex = "1"

[target.'cfg(windows)'.dependencies]
ansi_term = "0.12"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.65"
base64 = "0.11.0"
