name: Continuous integration

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
        include:
          - os: macOS-latest
            rust: 'stable'
            components: 'rustfmt, clippy'
            targets: 'x86_64-apple-darwin'
          - os: windows-latest
            rust: 'stable'
            components: 'rustfmt, clippy'
            targets: 'x86_64-pc-windows-msvc'
          - os: ubuntu-latest
            rust: 'stable'
            components: 'rustfmt, clippy'
            targets: 'x86_64-unknown-linux-musl'

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
